# fly.toml app configuration file generated for dynamic-dca on 2025-05-16T15:06:15+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dynamic-dca'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health_http]
    grace_period = '5s'
    interval = '30s'
    method = 'get'
    path = '/health'
    port = 3000
    timeout = '3s'
    type = 'http'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'

[[restart]]
  policy = 'on-failure'
  retries = 10
  processes = ['app']
